id: IF69FF8A7
initial_creation_type: ebook
source_metadata:
  id: MIN-MP-03
  title: ༄༅། ཟབ་ལམ་བདེ་གཤེགས་ཀུན་འདུས་ལས། མཁའ་འགྲོ་གསང་བ་ཡེ་ཤེས་ཀྱི་རྣལ་འབྱོར་རིམ་བཞིའི་ལམ་ཟབ་མོ་ཉམས་སུ་ལེན་པའི་ཁྲིད་ཡིག་མན་ངག་གསལ་སྒྲོན་ཞེས་བྱ་བ་བཞུགས་སོ།
  author: མཛད་པ་པོ། སྨིན་གླིང་རྗེ་བཙུན་མི་འགྱུར་དཔལ་སྒྲོན།
  authors: &id001
  - མཛད་པ་པོ། སྨིན་གླིང་རྗེ་བཙུན་མི་འགྱུར་དཔལ་སྒྲོན།
  sku: MIN-MP-03
  cover: MIN-MP-03.jpg
  volume: {}
ebook_metadata:
  title: ༄༅། ཟབ་ལམ་བདེ་གཤེགས་ཀུན་འདུས་ལས། མཁའ་འགྲོ་གསང་བ་ཡེ་ཤེས་ཀྱི་རྣལ་འབྱོར་རིམ་བཞིའི་ལམ་ཟབ་མོ་ཉམས་སུ་ལེན་པའི་ཁྲིད་ཡིག་མན་ངག་གསལ་སྒྲོན་ཞེས་བྱ་བ་བཞུགས་སོ།
  authors: *id001
  sku: MIN-MP-03
  cover: MIN-MP-03.jpg
layers:
- Author
- BookTitle
- Chapter
- Citation
- Commentary
- Sabche
